name: tekla-mcp-server

services:
  api:
    container_name: tekla-mcp-server
    build: .
    image: server:latest
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production 
      - ASPNETCORE_URLS=http://+:8080
      - DOTNET_RUNNING_IN_CONTAINER=true
    restart: always